stages:
  - build
  - push

task_runner_build:
  stage: build
  tags: 
    - "task-runner-shell"
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:latest .

task_runner_push:
  stage: push
  tags: 
    - "task-runner-shell"
  before_script:
    - echo "${CI_REGISTRY_PASSWORD}" | docker login ${CI_REGISTRY_IMAGE} --username ${CI_REGISTRY_PASSWORD} --password-stdin
  script:
    - docker push -t ${CI_REGISTRY_IMAGE}:latest

    