stages:
  - build
  - push

task_runner_build:
  stage: build
  tags: 
    - "task-runner-shell"
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:latest .
  only:
    - master

task_runner_push:
  stage: push
  tags: 
    - "task-runner-shell"
  before_script:
    - - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin
  script:
    - docker push ${CI_REGISTRY_IMAGE}:latest
  only:
    - master

